### ISSUE TITLE
Eroare la "cleanup"

### ISSUE THREAD

**Issue by MosfetWall** [KiralyCraft/FilelistCrawlerServerVersion#10]
[17:58] The.Wire.S04.1080p.BluRay.DD5.1.x264-CtrlHD - Checking requirements ...
[17:58] With this torrent, out total used space would be: 1014.869728528 GB.
[17:58] Not enough space to download The.Wire.S04.1080p.BluRay.DD5.1.x264-CtrlHD. It requires 75.32 GB
[17:58] Will ask Transmission to do a cleanup.
Should be removed: Utopia.AU.S03.720p.HDTV.x264-BTN
Should be removed: Dr.Strangelove.1964.1080p.BluRay.AC3.x264-HDC
Should be removed: Grease 1978 720p Blu-Ray DTS x264-REPTiLE
Should be removed: First.Man.2018.REPACK.1080p.UHD.BluRay.DD+7.1.HDR.x265.DON.mkv
[17:59] ERROR OCCURED! Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeCollapse(TimSort.java:441)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1462)
        at java.util.Collections.sort(Collections.java:175)
        at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:267)
        at com.kiralycraft.fcsv.torrentinterfaces.TransmissionInterface.cleanup(TransmissionInterface.java:60)
        at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:635)
        at com.kiralycraft.fcsv.RunThread.run(RunThread.java:163)

**Comment by MosfetWall** [comment]
[20:26] Will ask Transmission to do a cleanup.
Should be removed: Django.Unchained.2012.1080p.BluRay.DD5.1.x264-playHD
Should be removed: The.Outlaws.2017.720p.BluRay.DD.2.0.x264-MiBR
[20:28] ERROR OCCURED! null
java.lang.NullPointerException
        at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:243)
        at com.kiralycraft.fcsv.torrentinterfaces.TransmissionInterface.cleanup(TransmissionInterface.java:60)
        at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:635)
        at com.kiralycraft.fcsv.RunThread.run(RunThread.java:163)

**Comment by KiralyCraft** [comment]
Pare fixed
