### ISSUE TITLE
Connection Reset!

### ISSUE THREAD

**Issue by SHOBU007** [KiralyCraft/FilelistCrawlerServerVersion#5]
java -jar FilelistCrawlerServerVersion.jar
THIS ONLY WORKS IF PRESENT ON THE SAME PHYSICAL MACHINE AS TRANSMISSION!
You can type "help" to see various commands.
[01:21] Starting in progress
[01:21] Connecting to Transmission ...
[01:21] Connection to Transmission successfull
[01:21] Logging into Filelist.ro with username and password
[01:21] Acquiring CFDUID ...
[01:21] Error! null
[01:21] Clearing Torrent Cache ...
[01:21] Getting the 1st torrent page ...
[01:21] ERROR OCCURED! Connection reset
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
        at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at com.kiralycraft.fcsv.RunThread.getBrowsePage(RunThread.java:408)
        at com.kiralycraft.fcsv.RunThread.run(RunThread.java:147)

mentionez rulez prin run.bat specificat in tutorial si ca am acel .jar exact in directorul cu .bat

**Comment by KiralyCraft** [comment]
Ai pus toate setarile corect? Daca da, pe cate dispozitive esti conectat la filelist? Daca e mai mult de 3, probabil aici e problema. Pare sa fie o problema de la filelist. Vezi daca poti intra pe filelist.ro/browse.php de pe un browser instalat pe acelasi PC ca si aplicatia. Ce e ciudat e ca la mine merge, am verificat la 1:21 si pare ok.﻿

**Comment by SHOBU007** [comment]
Salut!

Mersi de raspuns! Am verificat si pot accesa filelist de pe un browser de pe acelasi pc. Sunt conectat de obicei de pe 1, maxim 2 dispozitive fiindca mai mereu ma conectez de pe alte ip-uri si asta ma delogheaza de pe filelist pe alte ip-uri decat ultimul logat. Iar ultimul logat ar trebui sa fie clientul de java, daca eu il execut, corect ? O sa dau sign out de pe toate si voi incerca si revin cu reply, probabil duoa ce ma trezesc mai sigur

EDIT1:

Revin cu raspuns, m-am delogat complet de pe filelist de pe toate dispozitivele, sau cel putin asa cred, dar acea eroare persista, m-am gandit ca poate e de la firewall, dar degeaba. o sa monitorizez cu un wireshark sa vad daca rezolv ceva. revin cu edit.

EDIT2:

Nu am observat nimic altceva decat conexiuni de reset cu wireshark fara prea multe indicii si m-am logat cu internet explorer,edge si firefox pe filelist si am reusit sa accesez filelist.ro/browse.php. Insa eroarea persista

EDIT3:

Am lasat cateva ore bune sistemul cu programul pornit si isi face verificarea la 10 minute dupa cum specifici in ultimul release insa eroarea persista. Mntionez ca sistemul pe care am rulat programul este un sistem x86, cu java, trasmission si restul aplicatiilor fiind tot pe 32 bit. Sper ca nu acest lucru cauzeaza problema.

**Comment by SHOBU007** [comment]
Oare ai un tutorial cu logarea prin browser cache ? Cel cu informatii despre campurile CFDUID etc.... ma redirectioneaza spre canalul tau, nu spre video.

**Comment by MosfetWall** [comment]
Incearca aici : https://www.youtube.com/watch?v=Zs5WOmdKiVo
Vezi tot filmul, la un moment explica si partea de login utilizand cookies.
Have fun

**Comment by KiralyCraft** [comment]
Cred ca am gasit problema. Pentru debugging, am lasat proxy activat ([https://github.com/KiralyCraft/FilelistCrawlerServerVersion/blob/master/FilelistCrawlerServerVersion/src/com/kiralycraft/fcsv/Main.java#L25](url)). Chiar daca nu asculta nimic pe 127.0.0.1:8888, JVM ar trebui sa renunte la proxy. Probabil la tine nu renunta, am sa fac un patch rapid acum in care rezolv aia, incearca asa. Fac si un release, si revin cu un edit cand e up.

EDIT: Am facut un release cu proxy optional. Incearca acum, poate merge.

**Comment by SHOBU007** [comment]
Salutare!

Problema a fost exact cea pe care ai sesizat-o! :D

Multumesc mult pentru rezolvare, acum funtioneaza cu logarea prin Username/Password.

Multumiri si lui MosfetWall pentru sugestie!

An nou fericit va urez!
