### ISSUE TITLE
Eroare cand este prea putin spatiu pe disk

### ISSUE THREAD

**Issue by SHOBU007** [KiralyCraft/FilelistCrawlerServerVersion#6]
Dupa o perioada de vreo 3 zile non stop de folosire, a reusit sa imi umple un hdd de cativa TB.

Problema insa a aparut recent, cand spatiul disponibil este insuficient..

Deci dupa cum spuneam, ruleaza normal pana apare asta...

[00:11] Avg upload speed: 1.4739511 MB/s. Upload potential 23%
[00:12] Avg upload speed: 3.028912 MB/s. Upload potential 48%
[00:12] Avg upload speed: 2.4762194 MB/s. Upload potential 39%
[00:12] Clearing Torrent Cache ...
[00:12] Getting the 1st torrent page ...
[00:12] Response Code : 200
[00:12] Grabbing torrent data ...
[00:12] Analyzing results ...
[00:12] Asking Transmission how much free space there is.
[00:12] Got response: 2490368 bytes = 2 MB
[00:12] ==========================================
[00:12] The.Curse.1987.720p.BluRay.x264-CREEPSHOW - Checking requirements ...
[00:12] Not enough space to download The.Curse.1987.720p.BluRay.x264-CREEPSHOW. It requires 4.41 GB
[00:12] Will ask Transmission to do a cleanup.
Removing torrent instance from Transmission
Removing associated files for:UFC.The.Evolution.of.CM.Punk.S01.720p.HDTV.DD5.1.MPEG2-NTb
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.google.gson.JsonArray.get(JsonArray.java:92)
        at com.kiralycraft.tapidiy.Connection.getTorrentFiles(Connection.java:613)
        at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:215)
        at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:589)
        at com.kiralycraft.fcsv.RunThread.run(RunThread.java:150)
[00:12] ERROR OCCURED! null
java.lang.NullPointerException
        at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:216)
        at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:589)
        at com.kiralycraft.fcsv.RunThread.run(RunThread.java:150)
[00:22] Clearing Torrent Cache ...
[00:22] Getting the 1st torrent page ...
[00:22] Response Code : 200
[00:22] Grabbing torrent data ...
[00:22] Analyzing results ...
[00:22] Asking Transmission how much free space there is.
[00:23] Got response: 2490368 bytes = 2 MB
[00:23] ==========================================
[00:23] The.Curse.1987.720p.BluRay.x264-CREEPSHOW - Checking requirements ...
[00:23] Not enough space to download The.Curse.1987.720p.BluRay.x264-CREEPSHOW. It requires 4.41 GB
[00:23] Will ask Transmission to do a cleanup.
Removing torrent instance from Transmission
Removing associated files for:Hospital.S01.720p.iP.WEBRip.AAC2.0.H.264-RTN
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.google.gson.JsonArray.get(JsonArray.java:92)
        at com.kiralycraft.tapidiy.Connection.getTorrentFiles(Connection.java:613)
        at com.kiralycraft.tapidiy.Connection.cleanup(Connection.java:215)
        at com.kiralycraft.fcsv.RunThread.parseTorrentData(RunThread.java:589)

**Comment by SHOBU007** [comment]
Iar acum nu poate face cleanup aparent. 

Codul mai jos.

[15:27] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:27] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:28] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:28] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:28] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:29] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:29] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:29] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:30] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:30] Clearing Torrent Cache ...
[15:30] Getting the 1st torrent page ...
[15:30] Response Code : 200
[15:30] Grabbing torrent data ...
[15:30] Analyzing results ...
[15:30] Asking Transmission how much free space there is.
[15:30] Got response: 6029312 bytes = 5 MB
[15:30] ==========================================
[15:30] Shtisel.S02.720p.NF.WEB-DL.DDP2.0.x264-NYH - Checking requirements ...
[15:30] Not enough space to download Shtisel.S02.720p.NF.WEB-DL.DDP2.0.x264-NYH. It requires 7.62 GB
[15:30] Will ask Transmission to do a cleanup.
[15:30] Transmission failed to clean up enough space for this torrent, so we're skipping it.
[15:30] ==========================================
[15:30]
[15:30] Analysis complete. Torrents that meet the requirements: 0 out of 50
[15:30] Now uploading to Transmission ...
[15:30] Asking Transmission where to store the torrent
[15:30] Transmission replied with: "F:\Torrente"
[15:30] Upload done! 0 / 0
[15:30] Got cookies from Filelist.ro. Will use those instead next time.
[15:30] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:30] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:31] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:31] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:31] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:32] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:32] Avg upload speed: 0.0 MB/s. Upload potential 0%
[15:32] Avg upload speed: 0.0 MB/s. Upload potential 0%

EDIT1:

M-am uitat in Transmission UI si aparent transmission sterge torrentele din UI sau le dezaloca de la seed dar NU le sterge de pe disk, de aia zice disk plin. restul care incearca sa le stearga sunt PAUSED..

Nu le-am pus eu pe pauza, de mentionat, si nici nu sunt complet descarcate!

EDIT2:

Am verificat la setari de download in Transmission si aveam keep incomplete files in some folder bifat, probabil de asta nu dispareau cele incomplete (cel mai probabil) grija pentru altii care intampina astfel de problema. cat despre cele care dispar din UI dar nu de pe disk nu stiu de ce inca...

**Comment by KiralyCraft** [comment]
Imi cer scuze ca a durat atat sa raspund, dar am facut acum un release cu ultimele commit-uri. Am reparat majoritatea probelemelor de la cleanup si ar trebui sa mearga bine acum. Daca nu merge in modul local, incearca sa descrii adresa de transmisison ca fiind IP-ul PC-ului tau. Ex: inloc de 127.0.0.1, pune 192.168.0.101 sau cat o fi.

**Comment by SHOBU007** [comment]
Salutare!

Scuze ca raspund atat de tarziu, Am vrut sa las ultima versiune o perioada mai lunga la testat si intradevar problemele leagte de clean sunt complet rezolvate (cel putin pt mine).

Multumesc pentru ajutor si promptitudine! :+1:
